version: "3.7"
services:
  web:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: web
    container_name: lista-tarefas-web
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./logs:/var/www/storage/logs
    networks:
      - lista-tarefas
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: lista-tarefas-nginx
    restart: unless-stopped
    ports:
      - 8086:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - lista-tarefas

  db:
    image: mysql:latest
    container_name: lista-tarefas-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d 
    ports:
      - 3307:3306 
    networks:
      - lista-tarefas
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin5
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
    networks:
      - lista-tarefas
  redis:
    image: 'redis:latest'
    container_name: 'lista-tarefas-redis'
    restart: 'always'
    environment:
        REDIS_HOST : cache
        REDIS_PORT : '${REDIS_PORT}'
        REDIS_PASSWORD : '${REDIS_PASSWORD}'
    command: 'redis-server --save 20 1 --loglevel warning --requirepass ''${REDIS_PASSWORD}'''
    volumes:
      - './:/var/www'
    networks:
      - lista-tarefas

  queue:
    build:
      args:
          user: jaciel
          uid: 1000
      context: ./
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    container_name: lista-tarefas-queue
    restart: unless-stopped
    volumes:
      - './:/var/www'
    depends_on:
      - redis
    networks:
      - lista-tarefas

  schedule:
    build:
      args:
          user: jaciel
          uid: 1000
      context: ./
      dockerfile: Dockerfile
    command: 'php artisan schedule:work'
    container_name: lista-tarefas-schedule
    restart: unless-stopped
    volumes:
      - './:/var/www'
    depends_on:
      - redis
      - queue
    networks:
      - lista-tarefas

  echo:
    build:
      args:
          user: jaciel
          uid: 1000
      context: ./
    volumes:
      - ./:/var/www
      - './laravel-echo-server.json:/app/laravel-echo-server.json'
    ports:
      - '${LARAVEL_ECHO_SERVER_PORT}:6001'
    restart: unless-stopped  
    command: 'laravel-echo-server start --force'  
    depends_on:
      - redis
    networks:
      - lista-tarefas            

networks:
  lista-tarefas:
    driver: bridge